replicaCount: 1

image:
  repository: registry.minter.network/honee-app-web
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: registry.minter.network

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

podSecurityContext: {}

securityContext: {}

service:
  port: 80

deployment:
  healthCheckPath: /

ingress:
  domain: ""
  tlsname: ""
  #issuer: letsencrypt-http
  clusterissuer: letsencrypt-prod

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
